// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.21.12
// source: api/recs/recs.proto

package recs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_api_recs_recs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_api_recs_recs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_api_recs_recs_proto_rawDescGZIP(), []int{0}
}

func (x *Tag) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Year  int32  `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	Tags  []*Tag `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_api_recs_recs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_api_recs_recs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_api_recs_recs_proto_rawDescGZIP(), []int{1}
}

func (x *Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Item) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Item) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Item) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type TagRating struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag    *Tag  `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Rating int32 `protobuf:"varint,2,opt,name=rating,proto3" json:"rating,omitempty"`
}

func (x *TagRating) Reset() {
	*x = TagRating{}
	mi := &file_api_recs_recs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagRating) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagRating) ProtoMessage() {}

func (x *TagRating) ProtoReflect() protoreflect.Message {
	mi := &file_api_recs_recs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagRating.ProtoReflect.Descriptor instead.
func (*TagRating) Descriptor() ([]byte, []int) {
	return file_api_recs_recs_proto_rawDescGZIP(), []int{2}
}

func (x *TagRating) GetTag() *Tag {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *TagRating) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type Perference struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     string       `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TagRatings []*TagRating `protobuf:"bytes,2,rep,name=tag_ratings,json=tagRatings,proto3" json:"tag_ratings,omitempty"`
}

func (x *Perference) Reset() {
	*x = Perference{}
	mi := &file_api_recs_recs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Perference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Perference) ProtoMessage() {}

func (x *Perference) ProtoReflect() protoreflect.Message {
	mi := &file_api_recs_recs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Perference.ProtoReflect.Descriptor instead.
func (*Perference) Descriptor() ([]byte, []int) {
	return file_api_recs_recs_proto_rawDescGZIP(), []int{3}
}

func (x *Perference) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Perference) GetTagRatings() []*TagRating {
	if x != nil {
		return x.TagRatings
	}
	return nil
}

var File_api_recs_recs_proto protoreflect.FileDescriptor

var file_api_recs_recs_proto_rawDesc = []byte{
	0x0a, 0x13, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x65, 0x63, 0x73, 0x2f, 0x72, 0x65, 0x63, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x72, 0x65, 0x63, 0x73, 0x22, 0x29, 0x0a, 0x03, 0x54,
	0x61, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x5f, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72, 0x12, 0x1d, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73,
	0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x72, 0x65, 0x63, 0x73, 0x2e, 0x54, 0x61,
	0x67, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x22, 0x40, 0x0a, 0x09, 0x54, 0x61, 0x67, 0x52, 0x61,
	0x74, 0x69, 0x6e, 0x67, 0x12, 0x1b, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x09, 0x2e, 0x72, 0x65, 0x63, 0x73, 0x2e, 0x54, 0x61, 0x67, 0x52, 0x03, 0x74, 0x61,
	0x67, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x22, 0x57, 0x0a, 0x0a, 0x50, 0x65, 0x72,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x30, 0x0a, 0x0b, 0x74, 0x61, 0x67, 0x5f, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x72, 0x65, 0x63, 0x73, 0x2e, 0x54, 0x61, 0x67,
	0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x0a, 0x74, 0x61, 0x67, 0x52, 0x61, 0x74, 0x69, 0x6e,
	0x67, 0x73, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x77, 0x65, 0x62, 0x62, 0x73, 0x61, 0x6c, 0x61, 0x64, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x79,
	0x61, 0x2d, 0x72, 0x65, 0x63, 0x73, 0x2d, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x72,
	0x65, 0x63, 0x73, 0x3b, 0x72, 0x65, 0x63, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_recs_recs_proto_rawDescOnce sync.Once
	file_api_recs_recs_proto_rawDescData = file_api_recs_recs_proto_rawDesc
)

func file_api_recs_recs_proto_rawDescGZIP() []byte {
	file_api_recs_recs_proto_rawDescOnce.Do(func() {
		file_api_recs_recs_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_recs_recs_proto_rawDescData)
	})
	return file_api_recs_recs_proto_rawDescData
}

var file_api_recs_recs_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_recs_recs_proto_goTypes = []any{
	(*Tag)(nil),        // 0: recs.Tag
	(*Item)(nil),       // 1: recs.Item
	(*TagRating)(nil),  // 2: recs.TagRating
	(*Perference)(nil), // 3: recs.Perference
}
var file_api_recs_recs_proto_depIdxs = []int32{
	0, // 0: recs.Item.tags:type_name -> recs.Tag
	0, // 1: recs.TagRating.tag:type_name -> recs.Tag
	2, // 2: recs.Perference.tag_ratings:type_name -> recs.TagRating
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_recs_recs_proto_init() }
func file_api_recs_recs_proto_init() {
	if File_api_recs_recs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_recs_recs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_recs_recs_proto_goTypes,
		DependencyIndexes: file_api_recs_recs_proto_depIdxs,
		MessageInfos:      file_api_recs_recs_proto_msgTypes,
	}.Build()
	File_api_recs_recs_proto = out.File
	file_api_recs_recs_proto_rawDesc = nil
	file_api_recs_recs_proto_goTypes = nil
	file_api_recs_recs_proto_depIdxs = nil
}
